//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.18 at 11:40:53 AM CEST 
//


package com.ricettadem.soap.annullaPrescritto;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ricettadem.soap.annullaPrescritto package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ricettadem.soap.annullaPrescritto
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AnnullaPrescrittoRichiesta }
     * 
     */
    public AnnullaPrescrittoRichiesta createAnnullaPrescrittoRichiesta() {
        return new AnnullaPrescrittoRichiesta();
    }

    /**
     * Create an instance of {@link ErroreRicettaType }
     * 
     */
    public ErroreRicettaType createErroreRicettaType() {
        return new ErroreRicettaType();
    }

    /**
     * Create an instance of {@link ElencoErroriRicetteType }
     * 
     */
    public ElencoErroriRicetteType createElencoErroriRicetteType() {
        return new ElencoErroriRicetteType();
    }

    /**
     * Create an instance of {@link DettaglioPrescrizioneType }
     * 
     */
    public DettaglioPrescrizioneType createDettaglioPrescrizioneType() {
        return new DettaglioPrescrizioneType();
    }

    /**
     * Create an instance of {@link ElencoDettagliPrescrizioniType }
     * 
     */
    public ElencoDettagliPrescrizioniType createElencoDettagliPrescrizioniType() {
        return new ElencoDettagliPrescrizioniType();
    }

    /**
     * Create an instance of {@link ComunicazioneType }
     * 
     */
    public ComunicazioneType createComunicazioneType() {
        return new ComunicazioneType();
    }

    /**
     * Create an instance of {@link ElencoComunicazioniType }
     * 
     */
    public ElencoComunicazioniType createElencoComunicazioniType() {
        return new ElencoComunicazioniType();
    }

    /**
     * Create an instance of {@link NotaType }
     * 
     */
    public NotaType createNotaType() {
        return new NotaType();
    }

    /**
     * Create an instance of {@link ElencoNotaType }
     * 
     */
    public ElencoNotaType createElencoNotaType() {
        return new ElencoNotaType();
    }

    /**
     * Create an instance of {@link AnnullaPrescrittoRicevuta }
     * 
     */
    public AnnullaPrescrittoRicevuta createAnnullaPrescrittoRicevuta() {
        return new AnnullaPrescrittoRicevuta();
    }

}
