//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.03 at 10:09:51 AM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://lottoricevuta.xsd.nre.mirsac.sanita.finanze.it", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ricettadem.soap.richiestaLottiNre;
