//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 10:39:14 AM CEST 
//


package com.ricettadem.soap.certificatiMalattia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 E' obbligatorio almeno uno tra gli elementi codiceDiagnosi e noteDiagnosi,
 *                 ma e' anche possibile inserirli tutti e due.
 *             
 * 
 * <p>Java class for diagnosi complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="diagnosi"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codiceDiagnosi" type="{http://cert.sanita.finanze.it/}codiceDiagnosi" minOccurs="0"/&gt;
 *         &lt;element name="noteDiagnosi" type="{http://cert.sanita.finanze.it/}string200" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "diagnosi", propOrder = {
    "codiceDiagnosi",
    "noteDiagnosi"
})
public class Diagnosi {

    protected String codiceDiagnosi;
    protected String noteDiagnosi;

    /**
     * Gets the value of the codiceDiagnosi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceDiagnosi() {
        return codiceDiagnosi;
    }

    /**
     * Sets the value of the codiceDiagnosi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceDiagnosi(String value) {
        this.codiceDiagnosi = value;
    }

    /**
     * Gets the value of the noteDiagnosi property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNoteDiagnosi() {
        return noteDiagnosi;
    }

    /**
     * Sets the value of the noteDiagnosi property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNoteDiagnosi(String value) {
        this.noteDiagnosi = value;
    }

}
