//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 10:39:14 AM CEST 
//


package com.ricettadem.soap.certificatiMalattia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 La data ricovero deve essere la stessa della comunicazione di inizio ricovero.
 *                 Giornata lavorata: se true indica che il lavoratore ha dichiarato di aver completato la propria attivita' lavorativa alla data del
 *                 ricovero,
 *                 false altrimenti.
 *                 Trauma: indica l'occorrenza di un evento traumatico.
 *             
 * 
 * <p>Java class for dimissione complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="dimissione"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ruoloMedico" type="{http://cert.sanita.finanze.it/}ruolo"/&gt;
 *         &lt;element name="dataRicovero" type="{http://cert.sanita.finanze.it/}dateString"/&gt;
 *         &lt;element name="dataDimissione" type="{http://cert.sanita.finanze.it/}dateString"/&gt;
 *         &lt;element name="dataFine" type="{http://cert.sanita.finanze.it/}dateString"/&gt;
 *         &lt;element name="tipoCertificato" type="{http://cert.sanita.finanze.it/}tipoCertificato"/&gt;
 *         &lt;element name="tipoRicovero" type="{http://cert.sanita.finanze.it/}tipoRicovero"/&gt;
 *         &lt;element name="diagnosi" type="{http://cert.sanita.finanze.it/}diagnosi"/&gt;
 *         &lt;element name="giornataLavorata" type="{http://cert.sanita.finanze.it/}booleanString" minOccurs="0"/&gt;
 *         &lt;element name="trauma" type="{http://cert.sanita.finanze.it/}booleanString" minOccurs="0"/&gt;
 *         &lt;element name="agevolazioni" type="{http://cert.sanita.finanze.it/}agevolazioni" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "dimissione", propOrder = {
    "ruoloMedico",
    "dataRicovero",
    "dataDimissione",
    "dataFine",
    "tipoCertificato",
    "tipoRicovero",
    "diagnosi",
    "giornataLavorata",
    "trauma",
    "agevolazioni"
})
public class Dimissione {

    @XmlElement(required = true)
    protected String ruoloMedico;
    @XmlElement(required = true)
    protected String dataRicovero;
    @XmlElement(required = true)
    protected String dataDimissione;
    @XmlElement(required = true)
    protected String dataFine;
    @XmlElement(required = true)
    protected String tipoCertificato;
    @XmlElement(required = true)
    protected String tipoRicovero;
    @XmlElement(required = true)
    protected Diagnosi diagnosi;
    protected String giornataLavorata;
    protected String trauma;
    protected String agevolazioni;

    /**
     * Gets the value of the ruoloMedico property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuoloMedico() {
        return ruoloMedico;
    }

    /**
     * Sets the value of the ruoloMedico property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuoloMedico(String value) {
        this.ruoloMedico = value;
    }

    /**
     * Gets the value of the dataRicovero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRicovero() {
        return dataRicovero;
    }

    /**
     * Sets the value of the dataRicovero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRicovero(String value) {
        this.dataRicovero = value;
    }

    /**
     * Gets the value of the dataDimissione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataDimissione() {
        return dataDimissione;
    }

    /**
     * Sets the value of the dataDimissione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataDimissione(String value) {
        this.dataDimissione = value;
    }

    /**
     * Gets the value of the dataFine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFine() {
        return dataFine;
    }

    /**
     * Sets the value of the dataFine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFine(String value) {
        this.dataFine = value;
    }

    /**
     * Gets the value of the tipoCertificato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoCertificato() {
        return tipoCertificato;
    }

    /**
     * Sets the value of the tipoCertificato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoCertificato(String value) {
        this.tipoCertificato = value;
    }

    /**
     * Gets the value of the tipoRicovero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoRicovero() {
        return tipoRicovero;
    }

    /**
     * Sets the value of the tipoRicovero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoRicovero(String value) {
        this.tipoRicovero = value;
    }

    /**
     * Gets the value of the diagnosi property.
     * 
     * @return
     *     possible object is
     *     {@link Diagnosi }
     *     
     */
    public Diagnosi getDiagnosi() {
        return diagnosi;
    }

    /**
     * Sets the value of the diagnosi property.
     * 
     * @param value
     *     allowed object is
     *     {@link Diagnosi }
     *     
     */
    public void setDiagnosi(Diagnosi value) {
        this.diagnosi = value;
    }

    /**
     * Gets the value of the giornataLavorata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiornataLavorata() {
        return giornataLavorata;
    }

    /**
     * Sets the value of the giornataLavorata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiornataLavorata(String value) {
        this.giornataLavorata = value;
    }

    /**
     * Gets the value of the trauma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrauma() {
        return trauma;
    }

    /**
     * Sets the value of the trauma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrauma(String value) {
        this.trauma = value;
    }

    /**
     * Gets the value of the agevolazioni property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAgevolazioni() {
        return agevolazioni;
    }

    /**
     * Sets the value of the agevolazioni property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAgevolazioni(String value) {
        this.agevolazioni = value;
    }

}
