//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 10:39:14 AM CEST 
//


package com.ricettadem.soap.certificatiMalattia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://cert.sanita.finanze.it/}ricevuta"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ricevutaOkInterrogazioneLavoratore" type="{http://cert.sanita.finanze.it/}ricevutaOkInterrogazioneLavoratore" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ricevutaOkInterrogazioneLavoratore"
})
@XmlRootElement(name = "interrogazioneLavoratoreResponse")
public class InterrogazioneLavoratoreResponse
    extends Ricevuta
{

    protected RicevutaOkInterrogazioneLavoratore ricevutaOkInterrogazioneLavoratore;

    /**
     * Gets the value of the ricevutaOkInterrogazioneLavoratore property.
     * 
     * @return
     *     possible object is
     *     {@link RicevutaOkInterrogazioneLavoratore }
     *     
     */
    public RicevutaOkInterrogazioneLavoratore getRicevutaOkInterrogazioneLavoratore() {
        return ricevutaOkInterrogazioneLavoratore;
    }

    /**
     * Sets the value of the ricevutaOkInterrogazioneLavoratore property.
     * 
     * @param value
     *     allowed object is
     *     {@link RicevutaOkInterrogazioneLavoratore }
     *     
     */
    public void setRicevutaOkInterrogazioneLavoratore(RicevutaOkInterrogazioneLavoratore value) {
        this.ricevutaOkInterrogazioneLavoratore = value;
    }

}
