//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 10:39:14 AM CEST 
//


package com.ricettadem.soap.certificatiMalattia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Sottoinsieme dell'elemento malattia, utilizzato come risultato della funzione di ricerca.
 *             
 * 
 * <p>Java class for malattiaRidotta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="malattiaRidotta"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dataRilascio" type="{http://cert.sanita.finanze.it/}dateString"/&gt;
 *         &lt;element name="dataInizio" type="{http://cert.sanita.finanze.it/}dateString"/&gt;
 *         &lt;element name="dataFine" type="{http://cert.sanita.finanze.it/}dateString"/&gt;
 *         &lt;element name="visita" type="{http://cert.sanita.finanze.it/}tipoVisita"/&gt;
 *         &lt;element name="tipoCertificato" type="{http://cert.sanita.finanze.it/}tipoCertificato"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "malattiaRidotta", propOrder = {
    "dataRilascio",
    "dataInizio",
    "dataFine",
    "visita",
    "tipoCertificato"
})
public class MalattiaRidotta {

    @XmlElement(required = true)
    protected String dataRilascio;
    @XmlElement(required = true)
    protected String dataInizio;
    @XmlElement(required = true)
    protected String dataFine;
    @XmlElement(required = true)
    protected String visita;
    @XmlElement(required = true)
    protected String tipoCertificato;

    /**
     * Gets the value of the dataRilascio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRilascio() {
        return dataRilascio;
    }

    /**
     * Sets the value of the dataRilascio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRilascio(String value) {
        this.dataRilascio = value;
    }

    /**
     * Gets the value of the dataInizio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataInizio() {
        return dataInizio;
    }

    /**
     * Sets the value of the dataInizio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataInizio(String value) {
        this.dataInizio = value;
    }

    /**
     * Gets the value of the dataFine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFine() {
        return dataFine;
    }

    /**
     * Sets the value of the dataFine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFine(String value) {
        this.dataFine = value;
    }

    /**
     * Gets the value of the visita property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVisita() {
        return visita;
    }

    /**
     * Sets the value of the visita property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVisita(String value) {
        this.visita = value;
    }

    /**
     * Gets the value of the tipoCertificato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoCertificato() {
        return tipoCertificato;
    }

    /**
     * Sets the value of the tipoCertificato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoCertificato(String value) {
        this.tipoCertificato = value;
    }

}
