//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 10:39:14 AM CEST 
//


package com.ricettadem.soap.certificatiMalattia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Medico che redige il certificato di malattia
 *                 oppure operatore che redige la comunicazione di inizio ricovero.
 *                 Se l'utente è una regione è obbligatorio impostare l'elemento codiceFiscale
 *                 per specificare il medico oppure l'operatore per cui si sta inviando il certificato
 *                 o la comunicazione e l'elemento pincode non deve essere impostato.
 *                 Se l'utente è un medico è obbligatorio l'elemento pincode e l'elemento codiceFiscale non deve essere impostato. Il
 *                 pincode deve essere cifrato.
 *                 Se l'utente e' un operatore consultare la documentazione specifica del servizio di invio ricovero.
 *             
 * 
 * <p>Java class for redattore complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="redattore"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="codiceFiscale" type="{http://cert.sanita.finanze.it/}codiceFiscale" minOccurs="0"/&gt;
 *         &lt;element name="pincode" type="{http://cert.sanita.finanze.it/}string200" minOccurs="0"/&gt;
 *         &lt;element name="codiceRegione" type="{http://cert.sanita.finanze.it/}string3" minOccurs="0"/&gt;
 *         &lt;element name="codiceAsl" type="{http://cert.sanita.finanze.it/}string3" minOccurs="0"/&gt;
 *         &lt;element name="codiceStruttura" minOccurs="0"&gt;
 *           &lt;simpleType&gt;
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *               &lt;maxLength value="6"/&gt;
 *             &lt;/restriction&gt;
 *           &lt;/simpleType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "redattore", propOrder = {
    "codiceFiscale",
    "pincode",
    "codiceRegione",
    "codiceAsl",
    "codiceStruttura"
})
public class Redattore {

    protected String codiceFiscale;
    protected String pincode;
    protected String codiceRegione;
    protected String codiceAsl;
    protected String codiceStruttura;

    /**
     * Gets the value of the codiceFiscale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFiscale() {
        return codiceFiscale;
    }

    /**
     * Sets the value of the codiceFiscale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFiscale(String value) {
        this.codiceFiscale = value;
    }

    /**
     * Gets the value of the pincode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPincode() {
        return pincode;
    }

    /**
     * Sets the value of the pincode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPincode(String value) {
        this.pincode = value;
    }

    /**
     * Gets the value of the codiceRegione property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceRegione() {
        return codiceRegione;
    }

    /**
     * Sets the value of the codiceRegione property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceRegione(String value) {
        this.codiceRegione = value;
    }

    /**
     * Gets the value of the codiceAsl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceAsl() {
        return codiceAsl;
    }

    /**
     * Sets the value of the codiceAsl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceAsl(String value) {
        this.codiceAsl = value;
    }

    /**
     * Gets the value of the codiceStruttura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceStruttura() {
        return codiceStruttura;
    }

    /**
     * Sets the value of the codiceStruttura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceStruttura(String value) {
        this.codiceStruttura = value;
    }

}
