//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 10:39:14 AM CEST 
//


package com.ricettadem.soap.certificatiMalattia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ricevuta complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ricevuta"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ricevutaVarie" type="{http://cert.sanita.finanze.it/}ricevutaVarie" minOccurs="0"/&gt;
 *         &lt;element name="ricevutaInfo" type="{http://cert.sanita.finanze.it/}ricevutaInfo" minOccurs="0"/&gt;
 *         &lt;element name="ricevutaNonOk" type="{http://cert.sanita.finanze.it/}ricevutaNonOk" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ricevuta", propOrder = {
    "ricevutaVarie",
    "ricevutaInfo",
    "ricevutaNonOk"
})
@XmlSeeAlso({
    InterrogazioneLavoratoreResponse.class,
    RettificaDimissioneResponse.class,
    InvioDimissioneResponse.class,
    AnnullamentoRicoveroResponse.class,
    InvioRicoveroResponse.class,
    RistampaMalattiaResponse.class,
    RicercaMalattiaResponse.class,
    AnnullamentoMalattiaResponse.class,
    RettificaMalattiaResponse.class,
    InvioMalattiaResponse.class
})
public abstract class Ricevuta {

    protected RicevutaVarie ricevutaVarie;
    protected RicevutaInfo ricevutaInfo;
    protected RicevutaNonOk ricevutaNonOk;

    /**
     * Gets the value of the ricevutaVarie property.
     * 
     * @return
     *     possible object is
     *     {@link RicevutaVarie }
     *     
     */
    public RicevutaVarie getRicevutaVarie() {
        return ricevutaVarie;
    }

    /**
     * Sets the value of the ricevutaVarie property.
     * 
     * @param value
     *     allowed object is
     *     {@link RicevutaVarie }
     *     
     */
    public void setRicevutaVarie(RicevutaVarie value) {
        this.ricevutaVarie = value;
    }

    /**
     * Gets the value of the ricevutaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RicevutaInfo }
     *     
     */
    public RicevutaInfo getRicevutaInfo() {
        return ricevutaInfo;
    }

    /**
     * Sets the value of the ricevutaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RicevutaInfo }
     *     
     */
    public void setRicevutaInfo(RicevutaInfo value) {
        this.ricevutaInfo = value;
    }

    /**
     * Gets the value of the ricevutaNonOk property.
     * 
     * @return
     *     possible object is
     *     {@link RicevutaNonOk }
     *     
     */
    public RicevutaNonOk getRicevutaNonOk() {
        return ricevutaNonOk;
    }

    /**
     * Sets the value of the ricevutaNonOk property.
     * 
     * @param value
     *     allowed object is
     *     {@link RicevutaNonOk }
     *     
     */
    public void setRicevutaNonOk(RicevutaNonOk value) {
        this.ricevutaNonOk = value;
    }

}
