//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 10:39:14 AM CEST 
//


package com.ricettadem.soap.certificatiMalattia;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for ricevutaOkRicercaMalattia complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ricevutaOkRicercaMalattia"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="datiCertificato" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="idCertificato" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="dataRicezione" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
 *                   &lt;element name="annullato" type="{http://cert.sanita.finanze.it/}booleanString"/&gt;
 *                   &lt;element name="malattia" type="{http://cert.sanita.finanze.it/}malattiaRidotta"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ricevutaOkRicercaMalattia", propOrder = {
    "datiCertificato"
})
public class RicevutaOkRicercaMalattia {

    protected List<RicevutaOkRicercaMalattia.DatiCertificato> datiCertificato;

    /**
     * Gets the value of the datiCertificato property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datiCertificato property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatiCertificato().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RicevutaOkRicercaMalattia.DatiCertificato }
     * 
     * 
     */
    public List<RicevutaOkRicercaMalattia.DatiCertificato> getDatiCertificato() {
        if (datiCertificato == null) {
            datiCertificato = new ArrayList<RicevutaOkRicercaMalattia.DatiCertificato>();
        }
        return this.datiCertificato;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="idCertificato" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="dataRicezione" type="{http://www.w3.org/2001/XMLSchema}dateTime"/&gt;
     *         &lt;element name="annullato" type="{http://cert.sanita.finanze.it/}booleanString"/&gt;
     *         &lt;element name="malattia" type="{http://cert.sanita.finanze.it/}malattiaRidotta"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "idCertificato",
        "dataRicezione",
        "annullato",
        "malattia"
    })
    public static class DatiCertificato {

        @XmlElement(required = true)
        protected String idCertificato;
        @XmlElement(required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar dataRicezione;
        @XmlElement(required = true)
        protected String annullato;
        @XmlElement(required = true)
        protected MalattiaRidotta malattia;

        /**
         * Gets the value of the idCertificato property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getIdCertificato() {
            return idCertificato;
        }

        /**
         * Sets the value of the idCertificato property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setIdCertificato(String value) {
            this.idCertificato = value;
        }

        /**
         * Gets the value of the dataRicezione property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDataRicezione() {
            return dataRicezione;
        }

        /**
         * Sets the value of the dataRicezione property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDataRicezione(XMLGregorianCalendar value) {
            this.dataRicezione = value;
        }

        /**
         * Gets the value of the annullato property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getAnnullato() {
            return annullato;
        }

        /**
         * Sets the value of the annullato property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setAnnullato(String value) {
            this.annullato = value;
        }

        /**
         * Gets the value of the malattia property.
         * 
         * @return
         *     possible object is
         *     {@link MalattiaRidotta }
         *     
         */
        public MalattiaRidotta getMalattia() {
            return malattia;
        }

        /**
         * Sets the value of the malattia property.
         * 
         * @param value
         *     allowed object is
         *     {@link MalattiaRidotta }
         *     
         */
        public void setMalattia(MalattiaRidotta value) {
            this.malattia = value;
        }

    }

}
