//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 10:39:14 AM CEST 
//


package com.ricettadem.soap.certificatiMalattia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="medico" type="{http://cert.sanita.finanze.it/}redattore"/&gt;
 *         &lt;element name="lavoratore" type="{http://cert.sanita.finanze.it/}lavoratore"/&gt;
 *         &lt;element name="dataInizioRicerca" type="{http://cert.sanita.finanze.it/}dateString" minOccurs="0"/&gt;
 *         &lt;element name="dataFineRicerca" type="{http://cert.sanita.finanze.it/}dateString" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "medico",
    "lavoratore",
    "dataInizioRicerca",
    "dataFineRicerca"
})
@XmlRootElement(name = "ricercaMalattiaRequest")
public class RicercaMalattiaRequest {

    @XmlElement(required = true)
    protected Redattore medico;
    @XmlElement(required = true)
    protected Lavoratore lavoratore;
    protected String dataInizioRicerca;
    protected String dataFineRicerca;

    /**
     * Gets the value of the medico property.
     * 
     * @return
     *     possible object is
     *     {@link Redattore }
     *     
     */
    public Redattore getMedico() {
        return medico;
    }

    /**
     * Sets the value of the medico property.
     * 
     * @param value
     *     allowed object is
     *     {@link Redattore }
     *     
     */
    public void setMedico(Redattore value) {
        this.medico = value;
    }

    /**
     * Gets the value of the lavoratore property.
     * 
     * @return
     *     possible object is
     *     {@link Lavoratore }
     *     
     */
    public Lavoratore getLavoratore() {
        return lavoratore;
    }

    /**
     * Sets the value of the lavoratore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Lavoratore }
     *     
     */
    public void setLavoratore(Lavoratore value) {
        this.lavoratore = value;
    }

    /**
     * Gets the value of the dataInizioRicerca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataInizioRicerca() {
        return dataInizioRicerca;
    }

    /**
     * Sets the value of the dataInizioRicerca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataInizioRicerca(String value) {
        this.dataInizioRicerca = value;
    }

    /**
     * Gets the value of the dataFineRicerca property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataFineRicerca() {
        return dataFineRicerca;
    }

    /**
     * Sets the value of the dataFineRicerca property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataFineRicerca(String value) {
        this.dataFineRicerca = value;
    }

}
