//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.23 at 10:39:14 AM CEST 
//


package com.ricettadem.soap.certificatiMalattia;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Giornata lavorata: se true indica che il lavoratore ha dichiarato di aver completato la propria attivita' lavorativa alla data del
 *                 ricovero,
 *                 false altrimenti.
 *                 Trauma: indica l'occorrenza di un evento traumatico.
 *             
 * 
 * <p>Java class for ricovero complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ricovero"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="dataRicovero" type="{http://cert.sanita.finanze.it/}dateString"/&gt;
 *         &lt;element name="giornataLavorata" type="{http://cert.sanita.finanze.it/}booleanString" minOccurs="0"/&gt;
 *         &lt;element name="trauma" type="{http://cert.sanita.finanze.it/}booleanString" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ricovero", propOrder = {
    "dataRicovero",
    "giornataLavorata",
    "trauma"
})
public class Ricovero {

    @XmlElement(required = true)
    protected String dataRicovero;
    protected String giornataLavorata;
    protected String trauma;

    /**
     * Gets the value of the dataRicovero property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataRicovero() {
        return dataRicovero;
    }

    /**
     * Sets the value of the dataRicovero property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataRicovero(String value) {
        this.dataRicovero = value;
    }

    /**
     * Gets the value of the giornataLavorata property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGiornataLavorata() {
        return giornataLavorata;
    }

    /**
     * Sets the value of the giornataLavorata property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGiornataLavorata(String value) {
        this.giornataLavorata = value;
    }

    /**
     * Gets the value of the trauma property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTrauma() {
        return trauma;
    }

    /**
     * Sets the value of the trauma property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTrauma(String value) {
        this.trauma = value;
    }

}
